### PR TITLE
Devtools check fix

### LINKED ISSUE #25: Adapt repository to comply with `devtools::check()`

### PR DESCRIPTION
**Pull request by xtrojak**
This PR is an attempt to pass `devtools::check()` (#25) as required by #18, so we can eventually submit package to CRAN.

In order to submit the package to CRAN, it must not have any ERRORs or WARNINGs, and you want to ensure that there are as few NOTEs as possible ([source](https://rdrr.io/cran/devtools/man/check.html)).

Current status:

- **errors**: the only remaining error regarding running the tests is documented in #24.
- **warnings**: the package has some dependencies (direct and also recursive) on `RGL`, which requires graphical interface to display some 3D plots (see [rgl.init](https://www.rdocumentation.org/packages/rgl/versions/0.107.14/topics/rgl.init) for more details)
- **notes**: several notes are remaining related mostly to the fact how importing of libraries is treated in general

Finally, there are some undocumented arguments #26.

### CODE REVIEW

**Comment by hechth** [comment]
We don't necessarily require full CRAN support - passing the checks is also just a good overall quality control.

File: LICENSE [hunk 1]
```diff
@@ -1,339 +0,0 @@
-                    GNU GENERAL PUBLIC LICENSE
```
Comment (martenson) [inline LICENSE]: Why are we dropping license?

Comment (xtrojak) [reply LICENSE]: From what I understood [here](https://stackoverflow.com/a/56103764) and consequently [here](https://r-pkgs.org/description.html#license) the license file is not needed if it is a standard one (like in our case).

More details - it is also possible to use `License: GPL(>=2) + file LICENSE` in DESCRIPTION, but, again, I was aiming at CRAN support and it says "If you want to release your package to CRAN, you must pick a standard license" anyway.

What do you think?

Comment (martenson) [reply LICENSE]: I understand the CRAN requirements are specific, but this repository is not CRAN-specific. E.g. it is also going to be packaged in conda, it can be installed from source etc. The LICENSE file is well integrated with GitHub and provides extra info to contributors. Can we keep it in the root of the repo but exclude from the CRAN submission?

Comment (xtrojak) [reply LICENSE]: I guess we can do that, I restored the `LICENSE` file and change it in `DESCRIPTION` in 73facab.

**Review by martenson — APPROVED** [review]
LGTM, I suggest the version goes up at least the minor bit.

File: tests/testthat/test-hybrid.R [hunk 2]
```diff
@@ -5,8 +5,18 @@ test_that("basic hybrid test", {
   
   expected <- arrow::read_parquet('../testdata/hybrid_recovered_feature_sample_table.parquet')
   known_table <- arrow::read_parquet('../testdata/known_table.parquet')
+
```
Comment (martenson) [inline tests/testthat/test-hybrid.R:8]:
```suggestion
  
  # CRAN limits the number of cores available to packages to 2
  # source https://stackoverflow.com/questions/50571325/r-cran-check-fail-when-using-parallel-functions#50571533
```

File: tests/testthat/test-unsupervised.R [hunk 3]
```diff
@@ -5,7 +5,17 @@ test_that("basic unsupervised test", {
   
   expected <- arrow::read_parquet('../testdata/unsupervised_recovered_feature_sample_table.parquet')
```
Comment (martenson) [inline tests/testthat/test-unsupervised.R:7]:
```suggestion
  
  # CRAN limits the number of cores available to packages to 2
  # source https://stackoverflow.com/questions/50571325/r-cran-check-fail-when-using-parallel-functions#50571533
```

**Review by martenson — APPROVED** [review]
I added a comment and a source of an unusual construct we use here. We could also reduce the duplication and reuse this code.

**Comment by xtrojak** [comment]
> LGTM, I suggest the version goes up at least the minor bit.

Good idea! Done in e24cdc8.

**Review by hechth — APPROVED** [review]
I fixed a small bug related to a lack of exporting a library, but otherwise it seems good :)
